gameId: dea4b43a-2b49-43a5-b841-1f7a51e0b875

loginUrl: http://localhost:3000/auth/login
registerUrl: http://localhost:3000/auth/register
registerConfirmUrl: http://localhost:3000/auth/confirmregistration?id=
connectUrl: ws://localhost:3000/channel

startTimeout: 40
password: "123456"

bots:
  first: 48